import os
import sys
from io import BytesIO

# Add backend directory to path so we can import services and firebase
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from services import firebase_service
from utils.logger import get_logger

logger = get_logger(__name__)

def test_integration():
    logger.info("Starting Firebase Integration Tests...")

    test_doc_id = "integration-test-doc-123"
    
    # 1. Test Firestore Save
    logger.info("--- 1. Testing Firestore: save_document ---")
    test_data = {
        "name": "Integration Test Document",
        "description": "Generated by integration test script.",
        "status": "READY",
        "created_by": "Antigravity Assistant"
    }
    firebase_service.save_document(test_doc_id, test_data)
    logger.info("Firestore: Document saved successfully.")

    # 2. Test Firestore Get
    logger.info("--- 2. Testing Firestore: get_document ---")
    retrieved = firebase_service.get_document(test_doc_id)
    logger.info(f"Firestore: Retrieved document details: {retrieved}")
    if retrieved and retrieved.get("name") == test_data["name"]:
        logger.info("Firestore GET check: PASSED!")
    else:
        logger.error("Firestore GET check: FAILED!")

    # 3. Test Storage Upload
    logger.info("--- 3. Testing Storage: upload_file ---")
    file_content = b"This is a dummy PDF file content used for testing Inclusia Firebase Storage integration."
    file_stream = BytesIO(file_content)
    destination_path = f"documents/{test_doc_id}.pdf"
    
    public_url = firebase_service.upload_file(file_stream, destination_path, content_type="application/pdf")
    logger.info(f"Storage: File uploaded successfully. Public URL: {public_url}")

    # 4. Test Firestore Subcollection: save_chat_message
    logger.info("--- 4. Testing Firestore Subcollection: save_chat_message ---")
    chat_message = {
        "role": "user",
        "content": "Ini adalah pesan tes integrasi Firebase!"
    }
    firebase_service.save_chat_message(test_doc_id, chat_message)
    logger.info("Firestore: Chat message saved successfully.")

    # 5. Test Firestore Subcollection: get_chat_history
    logger.info("--- 5. Testing Firestore Subcollection: get_chat_history ---")
    history = firebase_service.get_chat_history(test_doc_id)
    logger.info(f"Firestore: Chat history retrieved: {history}")
    if len(history) > 0 and history[0].get("content") == chat_message["content"]:
        logger.info("Firestore Subcollection GET check: PASSED!")
    else:
        logger.error("Firestore Subcollection GET check: FAILED!")

    logger.info("\n=== All Tests Executed! ===")
    logger.info("Please verify the following in your Firebase Console:")
    logger.info(f"1. Firestore collection 'documents' contains a document with ID '{test_doc_id}'.")
    logger.info(f"2. That document has a subcollection 'messages' containing the test message.")
    logger.info(f"3. Firebase Storage contains a file at 'documents/{test_doc_id}.pdf'.")

if __name__ == "__main__":
    try:
        test_integration()
    except Exception as e:
        logger.critical(f"Integration test failed with critical error: {e}", exc_info=True)
        sys.exit(1)
